json.id @user.id
json.username @user.username
json.indoorsoutdoors @user.indoorsoutdoors
json.discipline @user.discipline
json.age @user.age
json.location @user.location
json.summary @user.summary
json.doing @user.doing
json.good_at @user.good_at
json.favorites @user.favorites
json.thinking @user.thinking
json.friday @user.friday
json.message_if @user.message_if
json.image_url asset_path(@user.image.url)
